### ISSUE TITLE
Gold can be Found in Structures Directly

### ISSUE THREAD

**Issue by EndlessLeo** [enmumne/Gregorian-Nightmares#1]
As part of your design, gold blocks and ores should not be directly found while they can be found in better strongholds. I'm not sure if this counts as an issue.
![image](https://github.com/enmumne/Gregorian-Nightmares/assets/150091799/49367b1e-ce49-4559-b635-fc30ce630d7a)

**Comment by enmumne** [comment]
Oh, you closed this one... But I guess I'll look into it.
